version: 2
updates:
  - package-ecosystem: pip
    directories:
      - /
      - /packages/extended-opentelemetry-semconv
      - /services/servicegraph-demo
      - /services/servicegraph-indexer
    schedule:
      interval: weekly
    open-pull-requests-limit: 5

  - package-ecosystem: maven
    directory: /services/otel-servicegraph-diff/runtime/java
    schedule:
      interval: weekly
    open-pull-requests-limit: 5

  - package-ecosystem: docker
    directories:
      - /services/otel-servicegraph-diff
      - /services/servicegraph-demo
      - /services/servicegraph-gremlin
      - /services/servicegraph-indexer
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: python
        versions:
          - ">=3.13"
      - dependency-name: eclipse-temurin
        versions:
          - ">=18"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - github-actions
